### ISSUE TITLE
Error on module install

### ISSUE THREAD

**Issue by ghost** [MrXofar/compendium-navigator#1]
When I try to install the mod from Froundry VTT I get this error.
![image](https://user-images.githubusercontent.com/79125274/192941517-0738d6d8-1ba4-4336-9a4b-620f82a73e3e.png)

**Comment by SirMotte** [comment]
I can confirm this behaviour.

![grafik](https://user-images.githubusercontent.com/82598692/192967050-eadd17cd-9b0d-4651-b7f4-36b48cbad1ce.png)

**Comment by caprichozow** [comment]
Same
![image](https://user-images.githubusercontent.com/109267376/193007006-78bccf05-730d-4d26-a7aa-e4b1c0ef5796.png)

**Comment by bearsy1** [comment]
This is just a guess, but I think @MrXofar is working on getting the initial release ready (in a working state, up to their standards). I infer this based on the sentiment expressed in the description/readme page ~~and due to the fact that no files are currently published under [releases](url).~~

So in the meantime, I think all we can do is wait patiently. I'm quite looking forward to using this in my foundry setup though!

**Comment by MrXofar** [comment]
Looking into this. Thanks for letting me know. 
I haven't tried installing it myself since I am currently working on it. But I will run it through the install process today.

**Comment by MrXofar** [comment]
Should be good to go now. I had incorrect link in download: section. 
Thanks for being patient. This is a really cool project and I hope to have it polished up soon. Regular job kinda taking priority right now. 

Works great with Actors and Items. I hope to have the other document types supported soon.

**Comment by bearsy1** [comment]
Good to hear it's being improved upon! Can't wait to see the module reach it's full potential!
